### ISSUE TITLE
رفرنس به dontasktoask.com

### ISSUE THREAD

**Issue by mohsenasm** [erfanmola/DontAskToAsk#13]
سلام، وقتتون بخیر

به نظرم می‌رسه که قسمتی از مطالب سایت و یا حتی اسم ریپو از این جا (و یا مرجعی که در آن ذکر شده) اقتباس شده.

https://github.com/maunium/dontasktoask.com/blob/master/LICENSE

_اگر این طور هست_، بهتر هست که کپی‌رایت را رعایت کرده و به آن ارجاع دهید. تنها تعهد کپی‌رایت این ریپو، ذکر نام و لایسنس آن است.

**Comment by erfanmola** [comment]
سلام وقت‌بخیر
رفرنس در فایل ReadMe اضافه شد
