### ISSUE TITLE
Complete other parts or at least link the english version

### ISSUE THREAD

**Issue by alimahdiyar** [erfanmola/DontAskToAsk#3]
Thanks for the good content you made available in Persian :)
I see some good links in "Other similar problems" section in English.
I think it's better if you also add links to those projects, too.

**Comment by erfanmola** [comment]
Thanks for your topic, 
Sure I will translate related projects like XY Problem and etc to persian too, the reason I didn't reference English projects is I have their translation task in TODO list, and soon it will be done <3

**Comment by erfanmola** [comment]
Added [XYProblem](https:/dontasktoask.ir/xyproblem.html) in the [last commit](https://github.com/erfanmola/DontAskToAsk/commit/7259d262932575f028160edb4127319939c0d8eb).

**Comment by alimahdiyar** [comment]
Thanks :)
