### ISSUE TITLE
امتحان select کردن متن

### ISSUE THREAD

**Issue by reza-keshavarz** [erfanmola/DontAskToAsk#4]
اینکه نمیذارید متن رو با موس انتخاب کرد خیلی آزاد دهنده س.

می دونم که دغدغه تون کپی نکردن متنه، اما راه واسه دور زدنش هست و خیلی ها هم بلدن و  انجام می دن.

ولی:
آدمای زیادی، از جمله من و احتمالا خود شما، موقع مطالعه از این امکان برای تسهیل مطالعه و نشانه گذاشتن موقعی که میخوان صفحه رو موقتا ترک کنن استفاده می کنن.
مسدود کردن این امکان در نهایت تجربه کاربر واقعی رو خراب می کنه.
باعث افت کیفیت تمرکز می شه.

و در نهایت:
روی اون هدف زیبا و با ارزشی که شما دارید، تاثیر منفی می ذاره.

**Comment by erfanmola** [comment]
سلام، بله درسته حق با شماست، تجربه خوبی برای کاربر نداره

حقیقتا این حالت no-select برای جلوگیری از کپی نیست، معمولا وقتی در یک وبسایت اگر متن های غیرمجتوایی سلکت بشن تجربه خوبی دریافت نمی‌کنم، این عادت از متن های غیرمحتوایی شروع شده و کم‌کم به متن های محتوایی هم سرایت کرده و ناخودآگاه غیرقابل سلکت می‌کنم

در اولین فرصت فیکس میشه این مورد

**Comment by erfanmola** [comment]
اصلاح شد، ممنون بابت بازخورد
