### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by TruncatedDinosour** [erfanmola/DontAskToAsk#6]
can I ask a question?

**Comment by erfanmola** [comment]
Hey, Sure, Here is a magic ball that will answer your question : DontAskToAsk.ir

**Comment by TruncatedDinosour** [comment]
> Hey, Sure, Here is a magic ball that will answer your question : DontAskToAsk.ir

Yes thank you, can I ask one more question?

**Comment by erfanmola** [comment]
> > Hey, Sure, Here is a magic ball that will answer your question : DontAskToAsk.ir
> 
> Yes thank you, can I ask one more question?

Sure you can, here is the magic ball again : DontAskToAsk.ir

FYI, I'd like to give furthermore explanation on how magic ball deals with the questions redirected to it : 
`echo question >> /dev/null 2>&1 && echo "DontAskToAsk.ir"`

**Comment by TruncatedDinosour** [comment]
> > > Hey, Sure, Here is a magic ball that will answer your question : DontAskToAsk.ir
> > 
> > 
> > Yes thank you, can I ask one more question?
> 
> Sure you can, here is the magic ball again : DontAskToAsk.ir
> 
> FYI, I'd like to give furthermore explanation on how magic ball deals with the questions redirected to it : `echo question >> /dev/null 2>&1 && echo "DontAskToAsk.ir"`

thx
